### ISSUE TITLE
【已解决】app闪退-授权管理已停止运行（小米 MIUI11.0.2）

### ISSUE THREAD

**Issue by YYelf** [mmjang/ankihelper#22]
app闪退-授权管理已停止运行
---
**机型：** 红米Note 4x
**系统：** MIUI11.0.2 （安卓版本7.0）
**anki划词助手版本：** 2.29.9 test （应该是的）
**下载时间：** 2019-12-22
**apk来源：** [https://coolapk.com/apk/com.mmjang.ankihelper](https://coolapk.com/apk/com.mmjang.ankihelper)

---
> 问题描述

软件闪退，打不开。打开app，手机立即弹出弹窗，提示：授权管理已停止运行。然后软件闪退。

> 已尝试无效的做法

- 所有的权限都给了， 无效
- 重启手机无效
- 重新下载，重新安装app无效

> 问题截图

![](https://raw.githubusercontent.com/Anilway/blogImg/master/2019-12-22/Screenshot_2019-12-22.jpg)

**Comment by grtjyh** [comment]
MIUI 11 20.2.28 开发版也遇到了这个问题
解决方案：开发者选项 --> 取消 “启用MIUI优化”选项 --> 对Anki划词助手进行授权（针对AnkiDriod） 
                   --> 重新打开“启用MIUI优化”选项  --> 可正常使用该软件

**Comment by lujun9972** [comment]
关闭MIUI优化后还是闪退

**Comment by YYelf** [comment]
已解决。需要给ankihelper添加权限：允许访问AnkiDroid的数据库。

MIUI用户可以参考下图操作步骤：（图片来自酷安用户评论）

> 补充：如果关闭MIUI优化后，进入不了应用信息。可以按如下步骤操作：
> 1. 在关闭MIUI的基础上， 卸载 anki 和 anki划词助手（卸载前记得做好词库备份）
> 2. 先安装anki划词助手, 在初次打开时，点击权限提示弹窗，进入安卓原生应用信息界面（不要关闭，退到后台）
> 3. 再安装anki
> 4. 再返回到划词助手的应用信息界面，找到其他权限，进入，选择允许访问AnkiDroid的数据库。即可。

![](https://raw.githubusercontent.com/Anilway/blogImg/master/2019-12-22/ankihelper.jpg)

**Comment by panmengguan** [comment]
> 已解决。需要给ankihelper添加权限：允许访问AnkiDroid的数据库。
> 
> MIUI用户可以参考下图操作步骤：（图片来自酷安用户评论）
> 
> > 补充：如果关闭MIUI优化后，进入不了应用信息。可以按如下步骤操作：
> > 
> > 1. 在关闭MIUI的基础上， 卸载 anki 和 anki划词助手（卸载前记得做好词库备份）
> > 2. 先安装anki划词助手, 在初次打开时，点击权限提示弹窗，进入安卓原生应用信息界面（不要关闭，退到后台）
> > 3. 再安装anki
> > 4. 再返回到划词助手的应用信息界面，找到其他权限，进入，选择允许访问AnkiDroid的数据库。即可。
> 
> ![](https://raw.githubusercontent.com/Anilway/blogImg/master/2019-12-22/ankihelper.jpg)

请问我是海信A5手机，每次点击划词方案配置的时候都会闪退，请问您知道这是什么原因吗？允许访问AnkiDroid数据库和允许访问手机存储的权限都给了。。
